[package]
name = "frostgate-circuits"
version = "0.1.0"
edition = "2021"
authors = ["Frostgate Labs"]
license = "Apache-2.0"
description = "Zero-knowledge circuit implementations for Frostgate"

[dependencies]
sp1-zkvm = { workspace = true }
alloy-sol-types = { workspace = true }
frostgate-lib = { path = "../lib" }
serde = { workspace = true }
bincode = { workspace = true }
sha3 = "0.10"

[features]
default = ["std"]
std = [
    "alloy-sol-types/std",
    "serde/std",
]
